#!/usr/bin/env bash
# Generated by PCC workspace-configure workflow
#
# mumain-ctl: Project control script
#
# Usage: ./ctl <command>

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}▶${NC} $1"; }
log_success() { echo -e "${GREEN}✓${NC} $1"; }
log_warn() { echo -e "${YELLOW}⚠${NC} $1"; }
log_error() { echo -e "${RED}✗${NC} $1"; }

show_help() {
    cat << 'EOF'
mumain-ctl: Project control script

USAGE:
    ./ctl <command>

DEVELOPMENT COMMANDS:
    build           Build the game client (CMake + Ninja)
    test            Run tests
    lint            Run static analysis (cppcheck + clang-tidy)
    format          Auto-format code (clang-format)
    format-check    Check code formatting without modifying
    clean           Clean build artifacts (build/, build-mingw/, build-test/)
    check           Run quality gate (build + format-check + lint)

COMPONENTS:  mumain

EXAMPLES:
    ./ctl build                 # Build game client
    ./ctl check                 # Run full quality gate
    ./ctl format                # Auto-format all source files
    ./ctl lint                  # Run static analysis

EOF
}

# =============================================================================
# DEVELOPMENT COMMANDS
# =============================================================================

cmd_build() {
    log_info "Building mumain (Homebrew LLVM — Clang 22, catches -Werror + type errors)..."
    cmake -S MuMain -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang \
        -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ \
        && cmake --build build -j$(nproc)
    log_success "Build complete"
}

cmd_test() {
    log_info "Running mumain tests..."
    make -C MuMain test
    log_success "Tests complete"
}

cmd_lint() {
    log_info "Linting mumain..."
    make -C MuMain lint
    log_success "Lint complete"
}

cmd_format() {
    log_info "Formatting mumain..."
    make -C MuMain format
    log_success "Format complete"
}

cmd_format_check() {
    log_info "Checking mumain formatting..."
    make -C MuMain format-check
    log_success "Format check passed"
}

cmd_clean() {
    log_info "Cleaning mumain build artifacts..."
    rm -rf build build-mingw build-test
    log_success "Clean complete"
}

cmd_check() {
    log_info "Running mumain quality gate (build + format-check + lint)..."
    cmake -S MuMain -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang \
        -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++ \
        && cmake --build build -j$(nproc) \
        && make -C MuMain format-check \
        && make -C MuMain lint
    log_success "Quality gate passed"
}

# =============================================================================
# MAIN
# =============================================================================

case "${1:-help}" in
    build)
        cmd_build
        ;;
    test)
        cmd_test
        ;;
    lint)
        cmd_lint
        ;;
    format)
        cmd_format
        ;;
    format-check)
        cmd_format_check
        ;;
    clean)
        cmd_clean
        ;;
    check)
        cmd_check
        ;;
    help|--help|-h)
        show_help
        ;;
    *)
        log_error "Unknown command: $1"
        show_help
        exit 1
        ;;
esac
